export const userTips = [
	{
		icon: "/images/user-tick.svg",
		text: "Following",
		number: "5",
	},
	{
		icon: "/images/users.svg",
		text: "Followers",
		number: "20",
	},
	{
		icon: "/images/star.svg",
		text: "Rate",
		number: "4.2",
	},
]

export const products = [
	{
		tabName: "products",
		tabData: [
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes, Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product1.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
			{
				text: "Jeep Car, new, used for only one time",
				image: "/images/product2.png",
				price: 1000,
				tip: "Live Auction",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: true,
			},
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product3.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
			{
				text: "Jeep Car, new, used for only one time",
				image: "/images/product4.png",
				price: 1000,
				tip: "Live Auction",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: true,
			},
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product3.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
			{
				text: "Jeep Car, new, used for only one time",
				image: "/images/product4.png",
				price: 1000,
				tip: "Live Auction",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: true,
			},
		],
	},
	{
		tabName: "articles",
		tabData: [
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product1.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
		],
	},
	{
		tabName: "reviews",
		tabData: [
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product1.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product1.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
			{
				text: "Six-piece clothing set (blouse - pants - hat and shoes",
				image: "/images/product1.png",
				price: 500,
				tip: "Hot Sale",
				day: 2,
				minuets: 50,
				hours: 10,
				isFavorite: false,
			},
		],
	},
]
